name: ImagineNations
favicon: null
layout_spectrum: 0.01258964091539383
typography_spectrum: 0.12452888465486467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.22487797611393034
  lightness: 0.418273200513795
  saturation: 0.26562747033312917
  rhythmicContrast: 0.33382661966606975
purpose: []
